[package]
name = "redis-app"
version = "0.1.0"
authors = ["Jil Sahm"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.8.3"
log = "0.4.14"
redis = { version = "0.20.0", features = ["cluster"] }