apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes-app-deployment
spec:
  selector:
    matchLabels:
      app: probes-app
  template:
    metadata:
      labels:
        app: probes-app
    spec:
      containers:
      - name: probes-app-container
        image: jsahm/probes-app:latest
        envFrom:
          - configMapRef:
              name: probes-app-config
        resources:
          limits:
            memory: "8Mi"
            cpu: "5m"
        ports:
        - containerPort: 8080
