apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes-app
spec:
  selector:
    matchLabels:
      app: probes-app
  template:
    metadata:
      labels:
        app: probes-app
    spec:
      containers:
      - name: probes-app-container
        image: jsahm/probes-app:0.2.0
        envFrom:
          - configMapRef:
              name: probes-app-config
        resources:
          limits:
            memory: "32Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: "/ready"
            port: 8080
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: "/health"
            port: 8080
          initialDelaySeconds: 30
