apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-app
spec:
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
      - name: monitoring-app
        image: jsahm/monitoring-app:0.1.0
        resources:
          limits:
            memory: "32Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
