apiVersion: v1
kind: Service
metadata:
  name: redis-single-external
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30010
    name: client
  selector:
    app: redis-single